remove zstyles for the old up/down bindings from zshrc; add start-tmux style to zshrc; add "do you use tmux?" to the installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -122,6 +122,34 @@ while 'true'; do
   esac
 done
 
+>&2 'printf' '\033[H\033[2J'
+>&2 'printf' 'Do you use \033[1mtmux\033[0m?\n'
+>&2 'printf' '\n'
+>&2 'printf' '  \033[1m(1)\033[0m  Yes.\n'
+>&2 'printf' '  \033[1m(2)\033[0m  No.\n'
+>&2 'printf' '  \033[1m(q)\033[0m  Quit and do nothing.\n'
+>&2 'printf' '\n'
+while 'true'; do
+  >&2 'printf' '\033[1mChoice [12q]:\033[0m '
+  IFS='' 'read' '-r' 'choice'
+  case "$choice" in
+    '1')
+      tmux='1'
+      'break'
+    ;;
+    '2')
+      tmux='0'
+      'break'
+    ;;
+    'q')
+      'exit' '1'
+    ;;
+    *)
+      >&2 'printf' '\033[33mz4h\033[0m: invalid choice: \033[31m%s\033[0m\n' "$choice"
+    ;;
+  esac
+done
+
 rcs=''
 
 for f in ~/'.zshenv' ~/'.zprofile' ~/'.zshrc' ~/'.zlogin' ~/'.zlogout'; do
@@ -184,7 +212,7 @@ zshenv=
 zshrc=
 z4h=
 
-'trap' '"trap" "-" "INT" "TERM" "EXIT"; "command" "rm" "-f" "--" "$zshenv" "$zshrc" "$z4h" 2>/dev/null' \
+'trap' '"trap" "-" "INT" "TERM" "EXIT"; "command" "rm" "-f" "--" "$zshenv" "$zshrc" "${zshrc:+$zshrc.bak}" "$z4h" 2>/dev/null' \
   'INT' 'TERM' 'EXIT'
 
 if command -v 'mktemp' >'/dev/null' 2>&1; then
@@ -223,6 +251,11 @@ if ! err="$($fetch "$zshrc" '--' "$url"/.zshrc"$zshrc_suffix" 2>&1)"; then
   >&2 'printf' "%s\n" "$err"
   >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "$url"/.zshrc"$zshrc_suffix"
   'exit' '1'
+fi
+
+if '[' "$tmux" '=' '1' ']'; then
+  'command' 'sed' '-i.bak' '-E' "s/ 'integrated'/ 'system'/" "$zshrc"
+  'command' 'rm' '-f' '--' "$zshrc".bak
 fi
 
 Z4H="${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans/v5"
