fix and prettify the installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,10 +47,10 @@ if '[' "$euid" '=' '0' ']'; then
   fi
 fi
 
->&2 'printf' '\033[33mz4h\033[0m: platform \033[32m%s\033[0m is supported\n' "$platform"
-
+>&2 'printf' '\033[H\033[2J'
+>&2 'printf' 'Greetings, Human!\n'
 >&2 'printf' '\n'
->&2 'printf' '\033[33mz4h\033[0m: what kind of \033[1mkeyboard\033[0m are you using?\n'
+>&2 'printf' 'What kind of \033[1mkeyboard\033[0m are you using?\n'
 >&2 'printf' '\n'
 >&2 'printf' '  \033[1m(1)\033[0m  Mac. It has \033[32mOption\033[0m key(s) and does not have \033[31mBackspace\033[0m.\n'
 >&2 'printf' '  \033[1m(2)\033[0m  PC.  It has \033[32mBackspace\033[0m key(s) and does not have \033[31mOption\033[0m.\n'
@@ -77,6 +77,8 @@ while 'true'; do
   esac
 done
 
+>&2 'printf' '\n'
+
 rcs=''
 
 for f in ~/'.zshenv' ~/'.zprofile' ~/'.zshrc' ~/'.zlogin' ~/'.zlogout'; do
@@ -90,7 +92,7 @@ backup_dir=''
 if '[' '-n' "$rcs" ']'; then
   backup_dir='zsh-backup'
   if command -v 'date' >'/dev/null' 2>&1; then
-    backup_dir="$backup_dir/$('command' 'date' '+%Y-%m-%d-%H-%M-%S')"
+    backup_dir="$backup_dir/$('command' 'date' '+%Y%m%d-%H%M%S')"
   fi
   if [ '-e' "$HOME/$backup_dir" ]; then
     i='1'
@@ -99,13 +101,16 @@ if '[' '-n' "$rcs" ']'; then
     done
     backup_dir="$backup_dir.$i"
   fi
-  >&2 'printf' '\033[33mz4h\033[0m: \033[32mz4h\033[0m startup files already exist\n'
+  >&2 'printf' '\033[H\033[2J'
+  >&2 'printf' 'You have the following Zsh startup files:\n'
   >&2 'printf' '\n'
   for f in $rcs; do
-    >&2 'printf' '    \033[4m~/%s\033[0m\n' "${f##*/}"
+    >&2 'printf' '    \033[4m~/%s\033[0m\n' "$f"
   done
   >&2 'printf' '\n'
-  >&2 'printf' '  \033[1m(1)\033[0m  Move them to \033[4m~/%s\033[0m\n' "$backup_dir"
+  >&2 'printf' 'What should I do with them?\n'
+  >&2 'printf' '\n'
+  >&2 'printf' '  \033[1m(1)\033[0m  Move them to \033[4m~/%s\033[0m. \033[1mRecommended\033[0m.\n' "$backup_dir"
   >&2 'printf' '  \033[1m(2)\033[0m  Delete them.\n'
   >&2 'printf' '  \033[1m(q)\033[0m  Quit and do nothing.\n'
   >&2 'printf' '\n'
@@ -133,16 +138,19 @@ fi
 
 zshenv=
 zshrc=
+z4h=
 
-'trap' '"trap" "-" "INT" "TERM" "EXIT"; "command" "rm" "-f" "--" "$zshenv" "$zshrc" 2>/dev/null' \
+'trap' '"trap" "-" "INT" "TERM" "EXIT"; "command" "rm" "-f" "--" "$zshenv" "$zshrc" "$z4h" 2>/dev/null' \
   'INT' 'TERM' 'EXIT'
 
 if command -v 'mktemp' >'/dev/null' 2>&1; then
   zshenv="$('command' 'mktemp' "$HOME"/.zshenv.XXXXXXXXXX)"
   zshrc="$('command' 'mktemp' "$HOME"/.zshrc.XXXXXXXXXX)"
+  z4h="$('command' 'mktemp' "$HOME"/.z4h.XXXXXXXXXX)"
 else
   zshenv="$HOME"/.zshenv.tmp."$$"
   zshrc="$HOME"/.zshrc.tmp."$$"
+  z4h="$HOME"/.z4h.tmp."$$"
 fi
 
 url='https://raw.githubusercontent.com/romkatv/zsh4humans/v4'
@@ -161,25 +169,6 @@ if ! err="$($fetch "$zshrc" '--' "$url"/.zshrc"$zshrc_suffix" 2>&1)"; then
   'exit' '1'
 fi
 
-if '[' '-n' "$backup_dir" ']'; then
-  'command' 'mkdir' '-p' '--' "$backup_dir"
-  for f in $rcs; do
-    'command' 'cp' '--' "$f" "$backup_dir"/
-  done
-fi
-
-if '[' '-n' "$rcs" ']'; then
-  'command' 'rm' '-f' '--' $rcs
-fi
-
-'command' 'mv' '--' "$zshenv" ~/'.zshenv'
-'command' 'mv' '--' "$zshrc" ~/'.zshrc'
-
-'trap' '-' 'INT' 'TERM' 'EXIT'
-
->&2 'printf' '\033[33mz4h\033[0m: bootstrapping \033[32mzsh\033[0m environment\n'
-
-Z4H_URL="https://raw.githubusercontent.com/romkatv/zsh4humans/v4"
 Z4H="${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans/v4"
 
 umask o-w
@@ -188,12 +177,31 @@ umask o-w
 'command' 'mkdir' '-p' -- "$Z4H"
 
 >&2 printf '\033[33mz4h\033[0m: fetching \033[4mz4h.zsh\033[0m\n'
-if ! err="$($fetch "$Z4H"/z4h.zsh.$$ '--' "$Z4H_URL" 2>&1)"; then
+if ! err="$($fetch "$z4h" '--' "$url"/z4h.zsh 2>&1)"; then
   >&2 'printf' "%s\n" "$err"
-  >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "$Z4H_URL"
+  >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "$url"/z4h.zsh
   'command' 'rm' '-rf' '--' "$Z4H" 2>'/dev/null'
   'exit' '1'
 fi
+
+if '[' '-n' "$backup_dir" ']'; then
+  'command' 'mkdir' '-p' '--' "$backup_dir"
+  for f in $rcs; do
+    'command' 'cp' '--' "$f" "$backup_dir"/
+  done
+fi
+
+if '[' '-n' "$rcs" ']'; then
+  ('cd' && 'command' 'rm' '-f' '--' $rcs ) || 'exit'
+fi
+
+'command' 'mv' '--' "$zshenv" ~/'.zshenv'
+'command' 'mv' '--' "$zshrc" ~/'.zshrc'
+'command' 'mv' '--' "$z4h" "$Z4H"/z4h.zsh
+
+'trap' '-' 'INT' 'TERM' 'EXIT'
+
+>&2 'printf' '\033[33mz4h\033[0m: bootstrapping \033[32mzsh\033[0m environment\n'
 
 'export' ZDOTDIR="$HOME"
 Z4H_BOOTSTRAPPING='1'
